# see https://geshan.com.np/blog/2022/02/mysql-docker-compose/
version: '3.8'
services:
  mysql-db:
    container_name: mysql-exchange-db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=exchanges_database
      - MYSQL_ROOT_PASSWORD=vialpopi
    ports:
      - '3308:3306'
    volumes:
      - mysql-exchange-db:/var/lib/mysql
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-exchange-db:
    driver: local
